### ISSUE TITLE
Add support for MarkClusterer(plus) API

### ISSUE THREAD

**Issue by jorgebsa** [tjkaal/GoogleMapsVaadin7#15]
MarkClusterer v3 
Reference: http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/docs/reference.html
![image](https://cloud.githubusercontent.com/assets/7410139/4156511/0e060930-3475-11e4-84a4-7a36f7292999.png)

MarkClustererPlus v3 
Reference: http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/docs/reference.html
![image](https://cloud.githubusercontent.com/assets/7410139/4156505/03a47472-3475-11e4-9909-3469a033ffcd.png)

**Comment by tjkaal** [comment]
An extension supporting some kind of marker clustering will be released one day (I wish). But this will most likely never be a direct part of the actual add-on.
