### ISSUE TITLE
Removing all polylines and all markers not working on 7.4 or above

### ISSUE THREAD

**Issue by russellhoff** [tjkaal/GoogleMapsVaadin7#24]
I came up with this issue while developing with your tool. Using the 7.4.x vaadin version removing all polylines and markers don't work properly.

Polylines aren't removed. Markers, unfortunately, are removed one by one per call: removeAllMarkers() first call results in the removal of the first marker, removeAllMarkers() second call results in the removal of the second marker, and so on...

**Comment by tjkaal** [comment]
This should be fixed in the current version.
