### ISSUE TITLE
Draw a circle by passing the center point and radius

### ISSUE THREAD

**Issue by tpratap** [tjkaal/GoogleMapsVaadin7#28]
Guys,

Can you please help us out on drawing the circle based on the latlong obj and radius.
I have tried out , but no solutions yet achieved.

Thanks,
Taps

**Comment by tjkaal** [comment]
Circles are not currently supported by the add-on. Hopefully at some point I'll have time to create 'Overlays Extension' that will add an extended support for different types of overlays.
