### ISSUE TITLE
com.vaadin.server.PaintException

### ISSUE THREAD

**Issue by ares242** [tjkaal/GoogleMapsVaadin7#3]
Hello Tjkaal,

When i use your addon frequently appears this exception,

com.vaadin.server.PaintException: Failed to serialize shared state for connector com.vaadin.tapio.googlemaps.GoogleMap (305): null

I am updating the map with a timer about each 30 seconds adding new markers , it runs normaly, but when one interact with the map it crashes.

**Comment by tjkaal** [comment]
Closing this since it seems that the issue has not persisted.
