### ISSUE TITLE
Use Direction to define a path 

### ISSUE THREAD

**Issue by ado2000** [tjkaal/GoogleMapsVaadin7#31]
Hi,

Good component, is it possible to use Directions to define a path ? 
For instance, i have 5 point and i should go there in the less distance or better path by car or bus

Thanks
Giovanni

**Comment by tjkaal** [comment]
Navigation and search functionalities are separate things that could be applied to the map but shouldn't most likely be part of it. 

If you want to investigate this further, I think that it should be possible to create an extension that would ask Google APIs for the directions and then apply them to the map. But this kind of geocoding and search functionalities will most likely never be a direct part of the map component.

**Comment by ado2000** [comment]
Hi,

Thanks for the answer,
so if i understand correctly, can create an astansion like Street View Extension for GoogleMaps Add-on

Thanks
