### ISSUE TITLE
There should be the option to select countries

### ISSUE THREAD

**Issue by EyKrass** [tjkaal/GoogleMapsVaadin7#33]
Hi,

first nice addon, congrats.

I need to select countries. The polygon tool is an awesome way to do that. It would be very pratical to have the option to select a country. Something like: 

// returns a polygon list of the borders of the united states
ArrayList<LatLon> points = new CountryPoints_US<>(); 
GoogleMapPolygon overlay = new GoogleMapPolygon(points,
        "#ae1f1f", 0.8, "#194915", 0.5, 3);
map.addPolygonOverlay(overlay);
 

Is there a plan to do something like that?

**Comment by tjkaal** [comment]
That's something that isn't definitely part of the addon. Anyone could make a separate project that has the borders of each country defined as polygons.
