### ISSUE TITLE
GoogleMaps Not loading in china

### ISSUE THREAD

**Issue by x-pkumar** [tjkaal/GoogleMapsVaadin7#34]
I'm using this plugin in my application since one year, now my application can be accessed worldwide. but in china google map not loading. How to solve it.

I read this https://developers.google.com/maps/faq?hl=en#china_ws_access but need to change url somewhere

please suggest any solution. thanks.

**Comment by tjkaal** [comment]
Will include a fix for this to the next minor release which will be out ASAP.

**Comment by tjkaal** [comment]
I've now added possibility to define API url via GoogleMap#setApiUrl(). The Chinese API doesn't seem to work for me so it can be still broken. 

Could you test it for me if I make a commit? Just add googleMap.setApiUrl("maps.google.cn"); as the second command, instantly after the initial construction.

**Comment by tjkaal** [comment]
Now available at master branch.

**Comment by tjkaal** [comment]
Ärr found a bug. Please do not test yet :)

**Comment by tjkaal** [comment]
Or not...it seems to use http instead of https automatically. Guess it should work now?
