### ISSUE TITLE
Map terrain is removed when i move

### ISSUE THREAD

**Issue by aluismarte** [tjkaal/GoogleMapsVaadin7#36]
I click map terrain on and if i move or do something map terrain is disabled

**Comment by bedinsky** [comment]
Hi,
I've got the same iusse. 
It seems that map is showed as RoadMap as default 
If map type is changed with google control map type, new map type is showed but any change on map (zoom, pan, click on marker) bring back to RoadMap type.

**Comment by tjkaal** [comment]
I'm planning of including a fix for this to the next update.

**Comment by tjkaal** [comment]
The issue has now been fixed in the latest snapshot.
