### ISSUE TITLE
When using Vaadin Component as InfoWindow content, component 'flashes' on screen.

### ISSUE THREAD

**Issue by aroneous** [tjkaal/GoogleMapsVaadin7#39]
When using a Vaadin Component as the content of an InfoWindow using method `GoogleMap#setInfoWindowContents`, often the component briefly appears directly on top of the map before it is appropriately positioned within the InfoWindow. I'm guessing some default rendering logic is kicking in before the widget can be properly placed within the InfoWindow frame?

In any case, it's unsightly. Could this flash be avoided, maybe by making the component invisible until it's properly positioned?

**Comment by thinwire** [comment]
No longer appears in our tests
